### ISSUE TITLE
KNN: changing p affects result contamination

### ISSUE THREAD

**Issue by Aroksak** [yzhao062/pyod#135]
Hi!

I have a dataset with ~44k samples. When I do
`y = KNN(contamination=0.05, method='largest', p=2, n_jobs=-1).fit(X).predict(X)`
I get approx 2200 detected outliers, which is close to desired 5%. Although, when I do
`y = KNN(contamination=0.05, method='largest', p=1, n_jobs=-1).fit(X).predict(X)`
I get only 490 outliers. 

Changing method to mean or median doesn't affect this behaviour.

**Comment by John-Almardeny** [comment]
From [Pyod Documentation](https://github.com/yzhao062/pyod/blob/master/pyod/models/knn.py):

> When p = 1, this is equivalent to using manhattan_distance (l1), and euclidean_distance (l2) for p = 2

The important question is: How many features you have in your dataset?

If you have a lot of features, the above-result then makes since, because Euclidean distance gives the minimum distance between two points whereas Manhattan distance is preferable to Euclidean distance in high dimensional data due to the curse of dimensionality. [Interesting Reference](https://bib.dbvis.de/uploadedFiles/155.pdf).

**Comment by Aroksak** [comment]
I have 14 numeric features. I wanted to use l1 because they are not homogeneous, and Euclidian distance doesn't seem to have any physical meaning in the case (even though I scaled all the features).

Thanks for the reference, however I still do not understand why I'm experiencing a drop in outliers _count_. I could've understood worse or better _quaility_ of detected outliers, but I still see no reason why I get 4-5 times less outliers in training dataset with the same contamination parameter.

**Comment by yzhao062** [comment]
I have a way to do a sanity check. What about printing out the outlier scores?

the way the algorithm marks it as outliers is based on the outlier ranking. My feeling is possibly the outlier scores are so close that the tie cannot be made.

If this is not the case, I will try to reproduce on some benchmark datasets.
