### ISSUE TITLE
func:`pyod.utils.data.visualize` is not existed

### ISSUE THREAD

**Issue by Gabrielvon** [yzhao062/Pyod#14]
Is this function `pyod.utils.data.visualize`  deprecated? I cannot import this function.

```
import sys
import pyod
In[]: sys.version
Out[]: '3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]'
In[]: pyod.utils.data.visualize(clf_name, X_train, X_test, y_train_pred, y_test_pred, show_figure=True, save_figure=False)

Traceback (most recent call last):

  File "<ipython-input-9-1628666df63a>", line 2, in <module>
    pyod.utils.data.visualize(clf_name,

AttributeError: module 'pyod.utils.data' has no attribute 'visualize'
```
```
 (py36) E:\MyNutshell>pip show pyod                                   
Name: pyod                                                           
Version: 0.5.6                                                       
Summary: A Python Outlier Detection (Anomaly Detection) Toolbox      
Home-page: https://github.com/yzhao062/Pyod                          
Author: Yue Zhao                                                     
Author-email: yuezhao@cs.toronto.edu                                 
License: UNKNOWN             
```

**Comment by yzhao062** [comment]
Hi Gabriel,

pyod.utils.data.visualize is actually moved to example files instead, such as https://github.com/yzhao062/Pyod/blob/master/examples/knn_example.py . The reason is to eliminate the dependency of matplotlib.

In other words, you do not need to import that method from pyod.utils.data, but directly copy the visualize method contained in all example files.
![image](https://user-images.githubusercontent.com/15079146/43750828-312cd13e-99c8-11e8-9afe-8b495b383247.png)

Could you also report where did you see the documentation mentioning to use pyod.utils.data.visualize? I may forget to update that documentation. You may also want to update to the latest version of PyOD as well.

Thanks.

Yue

**Comment by Gabrielvon** [comment]
@yzhao062  Thanks for your prompt reply. I found it in the [documentation pages here](https://pyod.readthedocs.io/en/latest/example.html?#knn-example), but I have no ideas if it also appears in this repos.

![image](https://user-images.githubusercontent.com/8952869/43756766-b12baff6-9a48-11e8-9433-4831d26e7eb2.png)
