### ISSUE TITLE
Correct handling of LOF proba predictions

### ISSUE THREAD

**Issue by alexHeu** [yzhao062/pyod#16]
Hi,

thanks for the great library.
When evaluating whether it is usable for my work i stumbled across an potential issue.
My workflow looks as follows:
1. Train the LOF detector on a training dataset.
2. Provide raw scores and outlier probabilites for this set
3. Deploy the model to generate outlier probabilities on new data

Im not quite sure how to correctly perform step 2. By executing lof.predict_proba(train) it executes lof.decision_function(train) which delegates to the sklearn implementation. In sklearn it explicitely states that this function is only supposed to handle new data (https://github.com/scikit-learn/scikit-learn/blob/f0ab589f/sklearn/neighbors/lof.py#L233) which is violated here. 

Thanks for your help
Alex

**Comment by yzhao062** [comment]
Hey Alex,

Sorry for the delayed response as I was away for attending a conference.
You raised a valid point which I do acknowledge: LOF and similar methods always face a dilemma that how to do "prediction" properly.

Those methods are designed for fitting and generating the results on the original data in one-shot, instead of fitting and then predicting on new datasets. That is why sklearn LOF explains that "predict" function is kept private since it was not designed for that purpose. Therefore, it is always advised that combining training and test data to refit the model like this. However, it is noted that the data distribution may be changed after the combination, and the computational complexity is very high.

After some thinking, I believe the current approach is valid, even not perfect:
1. fit an lof model with the training data
2. call predict_proba on the training data
3. call predict_proba on the test data 

The result should not be very off as long as the training and test are sharing a similar distribution.
Hope this helps,

Yue
