### ISSUE TITLE
Linear Model Deviation-base Outlier Detection isn't setting 'random_state'

### ISSUE THREAD

**Issue by jm4rc05** [yzhao062/pyod#307]
I'm calling `LMDD(contamination=outliers_fraction,random_state=42)` and from `.get_params(deep=True)` I got:

```
{'contamination': 0.37894127856522997, 'dis_measure': 'aad', 'n_iter': 50, 'random_state': None}
```

thanks for the great work.

**Comment by John-Almardeny** [comment]
Thanks for your query.

That is because the variable name, in the implementation, is `self.random_state_` with an underscore at the end.

I can change it right now, yet I do not know if this would make it incompatible with Scikit learn, as in [this similar query](https://github.com/yzhao062/pyod/issues/241#issuecomment-716083678). 

Escalated to @yzhao062.

Regards,
Yahya.

**Comment by yzhao062** [comment]
sorry I was caught by developing new things at the moment. Let me see if this can be fixed in a few minutes now :) thanks both for the thought!
