### ISSUE TITLE
No anomalies detected using COPOD

### ISSUE THREAD

**Issue by iDestro** [yzhao062/pyod#360]
x:[110592,1]
contamination=0.001
The number of classification as 1 is 0? Is it working properly?

**Comment by yzhao062** [comment]
the number of 1 should be 110592*0.001 = 111
if you find there is no 1 in the classification result, I guess it is because the top 111 samples outlier scores are the same...

[0.1, 0.2, 0.3, 0.4, 0.5], contamination =0.4 -> [0,0,0,1,1]

however,

[0.1, 0.1, 0.2, 0.2, 0.2]. contimation =0.4 -> ？ the result can be confusing.

I think in this case do not use copod, while only 1 feature you may not need to use any outlier detection method, but simple check the distance to the mean or median should be fine.

**Comment by yzhao062** [comment]
actually that is how it is done, top n samples with the highest outlier scores.
n = total sample size * contamination rate

I guess COPOD's raw score in your case is suspicious, maybe many samples have the same score.
