### ISSUE TITLE
What is difference between Scikit One Class SVM vs PYOD One Class SVM?

### ISSUE THREAD

**Issue by vchouksey** [yzhao062/Pyod#4]
Running Scikit OCSVM gives me Results:

Best parameters: (Nu 0.1500000000 gamma 0.0) Precision score: 0.143 Recall score: 0.800

Running PYOD OCSVM gives me Results:

Best parameters: (Nu 0.0300000000 gamma 0.0) Precision score: 0.868 Recall score: 0.103

**Comment by yzhao062** [comment]
Actually they are **equivalent**. For **LOF**, **Isolation Forest** and **One-class SVM**, the pyod version is simply a wrapper of scikit-learn implementation since there is no point to reinvent the wheels.
However, there is still one difference worth mentioning. In scikit learn, outliers have smaller scores, while pyod has the totally different design (outliers have larger scores). This explains why you saw the result are significantly different. 
For example, if you have [0.1, 0.2, 0.3, 0.4] as the outlier scores and assume there is 1 outlier. Scikit learn will generate label as [1, 0, 0, 0], whereas pyod generates the label as [0, 0, 0, 1].  

From implementation perspective, I just flipped the scikit outputs by:
- multiply by -1
- or use max(scores) - scores

The reason to do this conversion is simply for consistency and intuition. All models in pyod follow the same logic: outliers come with higher outlier scores. This design helps when we try to combine multiple models.
