### ISSUE TITLE
XGBOD and LSCP missing from install

### ISSUE THREAD

**Issue by allendorf** [yzhao062/pyod#43]
I installed PyOD using: 

```
pip install pyod
pip install --upgrade pyod
```

However, LSCP and XGBOD are not installed. All of the other models in the repo can be successfully imported into a jupyter notebook. Attempting to import LSCP and XGBOD both yield a "ModuleNotFoundError: No module named" error.

**Comment by yzhao062** [comment]
Hi Allen,

Sorry for the confusion. XGBOD and LSCP are in pre-lease and in development branch only. So installing from pip would not get that. We are going to submit these two packages along with 2 neural-net models in V0.6.6 by this week. The only way to use these two models now is to check out the development branch...

Stay tuned:)
Best,

Yue

**Comment by yzhao062** [comment]
Happy to provide an update. XGBOD and LSCP are included in #44 & pre-lease v.0.6.6b1 (https://pypi.org/project/pyod/0.6.6b1/) and planned to be released in v0.6.6 later this week (likely to be this Sat). If you would like to try the pre-release, then

pip install pyod==0.6.6b1

Otherwise, please wait for 4 more days for an official release... Besides, 2 neural-net based models are also included in this pre-release and the stable version later this week.
