### ISSUE TITLE
Error message with ABOD

### ISSUE THREAD

**Issue by mccoydj1** [yzhao062/pyod#450]
I'm trying to run the code below and I get an error message. I don't understand why the first example works fine but the second does not. Let me know your thoughts!

```
from pyod.models.abod import ABOD
import seaborn as sns
import pandas as pd

# This data works fine
abod_clf = ABOD(contamination=0.05)
df = sns.load_dataset('tips')
inputdf = df[['total_bill', 'tip']]
abod_clf.fit(inputdf)
print('Method 1 works!')

# This data does not work
abod_clf = ABOD(contamination=0.05)
inputdf = pd.DataFrame(data=[[30, 20], [50, 20], [40, 60]])
abod_clf.fit(inputdf)
print('Method 2 works! (note this line is not reached)')
```

Here's the error message that I get when I try to run it. What am I doing wrong?

```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function dot at 0x000001E6E775DB88>) found for signature:
 
 >>> dot(array(int64, 1d, C), array(int64, 1d, C))
 
There are 4 candidate implementations:
  - Of which 4 did not match due to:
  Overload in function '_OverloadWrapper._build.<locals>.ol_generated': File: numba\core\overload_glue.py: Line 129.
    With argument(s): '(array(int64, 1d, C), array(int64, 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: np.dot() only supported on float and complex arrays
  raised from C:\Users\mccoy\AppData\Local\PythonPlus\64bit\lib\site-packages\numba\core\typing\npydecl.py:920

During: resolving callee type: Function(<function dot at 0x000001E6E775DB88>)
During: typing of call at C:\Users\mccoy\AppData\Local\PythonPlus\64bit\lib\site-packages\pyod\models\abod.py (52)


File "..\..\..\..\..\..\..\AppData\Local\PythonPlus\64bit\lib\site-packages\pyod\models\abod.py", line 52:
def _wcos(curr_pt, a, b):  # pragma: no cover
    <source elided>
    wcos = np.dot(a_curr, b_curr) / (
            np.linalg.norm(a_curr, 2) ** 2) / (
            ^
```

**Comment by L-F-A** [comment]
If you look carefully at the error message I think you can find the answer you are looking for aka:

TypingError: np.dot() only supported on float and complex arrays

data=[[30, 20], [50, 20], [40, 60]] is a list of lists (array) of integers and will most likely be interpreted as such when used by numba. 

Try to just pass data that are floats. For example data=[[30.0, 20.0], [50.0, 20.0], [40.0, 60.0]]

If you want to try your code again, you will not get that error anymore, but it will still be problematic most likely because three data points is not enough. So to test, you can instead try something like:

# Below, this create a list of lists of integers like your data=[[30, 20], [50, 20], [40, 60]], but with 244 datapoints, the same 
# number as in sns.load_dataset('tips') that you used and with values between 10 and 100

data_randint = np.random.randint(10, 100, (244, 2))
data = [list(r) for r in data_randint]

# Now, instead of a list of lists of integers, lets transform it to a list of lists of float 

data1 = [list(r) for r in data_randint.astype(float)]

# Try your code on both data and data1 and see that data1 works:

# This will throw the error because of the integer nature of data
abod_clf = ABOD(contamination=0.05)
inputdf = pd.DataFrame(data=data)
abod_clf.fit(inputdf)

# This will work
abod_clf = ABOD(contamination=0.05)
inputdf = pd.DataFrame(data=data1)
abod_clf.fit(inputdf)
