### ISSUE TITLE
LSCP with multiple LOF testing error: range parameter must be finite

### ISSUE THREAD

**Issue by flycloudking** [yzhao062/pyod#70]
I am running the following code:

clf_name = 'LSCP_LOF'

## other parameters:
lof_list = [LOF(n_neighbors=5), LOF(n_neighbors=10), LOF(n_neighbors=20), LOF(n_neighbors=30), LOF(n_neighbors=40), LOF(n_neighbors=50), LOF(n_neighbors=75)]

clf = LSCP(lof_list)
#clf = LOF(n_neighbors=5, contamination=outliers_fraction)
clf.fit(X_train)

and got the following error, however, when fit directly with LOF method, it runs fine:

ValueError                                Traceback (most recent call last)
<ipython-input-27-6e00f8bf5bcd> in <module>()
     12 clf = LSCP(lof_list)
     13 #clf = LOF(n_neighbors=5, contamination=outliers_fraction)
---> 14 clf.fit(X_train)
     15 
     16 # get the prediction label and outlier scores of the training data

~/proj/myPylib/lib/python3.6/site-packages/pyod/models/lscp.py in fit(self, X, y)
    171 
    172         # set decision scores and threshold
--> 173         self.decision_scores_ = self._get_decision_scores(X)
    174         self._process_decision_scores()
    175 

~/proj/myPylib/lib/python3.6/site-packages/pyod/models/lscp.py in _get_decision_scores(self, X)
    273             pred_scores_ens[i,] = np.mean(
    274                 test_scores_norm[
--> 275                     i, self._get_competent_detectors(pearson_corr_scores)])
    276 
    277         return pred_scores_ens

~/proj/myPylib/lib/python3.6/site-packages/pyod/models/lscp.py in _get_competent_detectors(self, scores)
    355                           "classifiers, reducing n_bins to n_clf.")
    356             self.n_bins = self.n_clf
--> 357         hist, bin_edges = np.histogram(scores, bins=self.n_bins)
    358 
    359         # find n_selected largest bins

/opt/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py in histogram(a, bins, range, normed, weights, density)
    668     if not np.all(np.isfinite([first_edge, last_edge])):
    669         raise ValueError(
--> 670             'range parameter must be finite.')
    671     if first_edge == last_edge:
    672         first_edge -= 0.5

ValueError: range parameter must be finite.

Thanks

**Comment by yzhao062** [comment]
Thanks for the note. Is that possible for sharing the code as well? especially the underlying data.
Yue

**Comment by flycloudking** [comment]
please see attached zipped csv file, this is exactly the data for X_train. The code is all here except the library loading part.

[test.zip](https://github.com/yzhao062/pyod/files/3077808/test.zip)

**Comment by yzhao062** [comment]
This is related to https://github.com/scipy/scipy/issues/3728 regarding how Pearson scores are generated. LSCP relies on Pearson score to select the "best set of detectors". However, pearsonr in scipy will return nan if the input vectors are with zero variance. For instance,
X1: [1,2,3,4,5]
X2: [2,2,2,2,2]

Pearson is defined as cov(X1, X2)/sqrt(var(X1)var(X2)). In the given example, var(X2)=2 causes pearsonr(X1, X2) become infeasible (denominator=0) and return nan.

The Pearson scores are then passed in np.histogram to build histograms. This error can be overridden by adding the following two lines. This could force nans to zeros. :
![image](https://user-images.githubusercontent.com/15079146/56234984-705a5b80-6054-11e9-989a-6feda3b6dcb6.png)

I will think about how to handle this...this happens when data lacks variations and base detectors are also similar:

- Training samples receive similar scores
- base detectors generate similar results, e.g., lof detectors

Under this situation, the value of using LSCP for model combination is limited. that being said, using a simple combination might be preferred.

**Comment by yzhao062** [comment]
The latest commit is not yet pushed to master branch but development branch only (https://github.com/yzhao062/pyod/tree/development). The next release V0.7.0 will include this commit.

**Comment by yzhao062** [comment]
Closed by #84. Available in the latest version ([v0.7.0](https://pypi.org/project/pyod/)).
