### ISSUE TITLE
if n_samples is large , certain outlier model error rate 200% higher

### ISSUE THREAD

**Issue by Wang-Yong2018** [yzhao062/pyod#81]
Hi, YZhao;

I was writing to one possible isuue: in example notebooks compare all models, if the n_samples change to a big number, for example : 10*5 or larger. certain model OD result is totally wrong. 
Note: I noticed there is a similar issue. Problem in CBLOF when the number of clusters is big and the train set has too many repeated value #53. But my found should be differnet, so post is as well.

Here is isssue:
1. the default n_sample  =200, outlier_fraction = 0.25. That means od ground trun point is 50.  After change the n_sample to 10**5, the ground true outlier point should be 25000. 
However, following models error higher that the groud true OD points. they were:
Feature Bagging:  35259 
Local Outlier Factor (LOF) 36144 
Locally Selective Combination (LSCP) 37276
below is the screen capture.
![image](https://user-images.githubusercontent.com/36652035/56457810-aed47b00-63b2-11e9-9458-17ded1b9b156.png)

I guess it might related to the dataset type. Doest it mean the simulation data similar to the 
"glass", "optdigits" sample date? why the other estimator did not show such higher error rate? 

Looking forward your kindly response！

Last but not least, I was know PYOD existed from zhihu. It is a excellent tools, especialy, I have access to more OD resources link for your github. Your work is awesome!

Recently, i has begun to try use some model it in one of my general OD automation tools.(which use docker, and airflow for platform).  dataset type, and dataset qty are two of point need considered.

WangYong
w.yong@yahoo.com

**Comment by yzhao062** [comment]
Hi Wang,

Interesting. LSCP example uses LOF as the base detectors so the result is not surprising if LOF fails to work.

My guess is the parameter choice. LOF depends on n_neighbors to define the local region. By the synthetic data we are using, 25,000 points are condensed and the locality assumption may be violated. What about using a larger n_neighbors in LOF. 

Would you able to share the actual code so I could take a look?
Thanks,

Yue

**Comment by Wang-Yong2018** [comment]
I just use the defauly notebook. Only change the n_samples number from 200 to 10**5.

This morning, I tried change the n_neighbour to sqrt of n_samples, but not feedback, not appropriate parameter for fitting. So, only change it to 100. Looks not significant improvoment yet.

Here is tow notebooks for your reference. 

[notebooks.zip](https://github.com/yzhao062/pyod/files/3100846/notebooks.zip)

**Comment by yzhao062** [comment]
Thanks for the info. Will do some investigation :) Stay tuned.

**Comment by yzhao062** [comment]
Hi there, 

I just checked the file and realized the example is just for demo purpose. The reason why certain models do not work is data dependent and impacted by the model parameter. 

when setting n==10^5, there are too many outliers (too condensed) as the generation algorithm is fixed the range in 0.3 * normal distribution. The local algorithms like LOF won't work well. Featurebagging and LSCP both use LOF as base detector so they fail to work as well.

However, if you let outliers to spread sparsely by setting outliers_fraction to a small number like below, they will work perfectly.

```
# Define the number of inliers and outliers
n_samples = 5000
outliers_fraction = 0.01
```

The ultimate cause is due to LOF's reachability definition, and you are welcome to take the original paper for more info:  http://www.dbs.ifi.lmu.de/Publikationen/Papers/LOF.pdf

![image](https://user-images.githubusercontent.com/15079146/56515065-008d1a80-6505-11e9-95c2-6a1e7427992c.png)

**Comment by Wang-Yong2018** [comment]
Hi, 

Thanks for you rapid answer. It do help me. Thank you. 

I will spend time to study the paper later.

**Comment by yzhao062** [comment]
Perfect. Feel free to drop any question.
