### ISSUE TITLE
CBLOF not converging expected different data type

### ISSUE THREAD

**Issue by wbarich** [yzhao062/pyod#89]
I have been unable to flag anomalies using this algorithm. I have found that when I run the CBLOF algorithm it throws the following error:

ValueError: Buffer dtype mismatch, expected 'INT' but got 'long long'

Exception ignored in: 'sklearn.cluster._k_means._assign_labels_csr' ValueError: Buffer dtype mismatch, expected 'INT' but got 'long long'

Which results in:

ValueError: Could not form valid cluster separation. Please change n_clusters or change clustering method

It appears that the CBLOF algorithm is dependent on sklearn.cluster and the expected data type that is being passed to skelearn from pyod is not what is expected.

Below are four scenarios that I have prepared using different parameters for CBLOF. Note that the same error is thrown regardless of changing theses parameters.

I have also tried changing the cluster size using the elbow method to find the optimal K in the Kmeans scenario.

    from pyod.models.cblof import CBLOF
    import pyod.utils as ut
    from sklearn import cluster

    #create some data
    data = ut.data.generate_data()[0]

    #scenario 1 - use default CBLOF parameters
    model = CBLOF()
    clusters = model.fit_predict(data)

    #scenario 2 - use kmeans as a centroid estimator
    n_clusters = 3
    kmeans = cluster.KMeans(n_clusters)
    model = CBLOF(n_clusters = n_clusters, clustering_estimator = kmeans)
    clusters = model.fit_predict(data)

    #test if scaling the data makes a difference
    data_scaled = (data - data.min())/(data.max()-data.min())

    #scenario 3 - no clusters specified, use defaults, scaled data
    model = CBLOF()
    clusters = model.fit_predict(data_scaled)

    #scenario 4 - use kmeans as a centroid estimator, scaled data
    n_clusters = 3
    kmeans = cluster.KMeans(n_clusters)
    model = CBLOF(n_clusters = n_clusters, clustering_estimator = kmeans)
    clusters = model.fit_predict(data_scaled)

**Comment by yzhao062** [comment]
Hi there,

If you have scikit-learn >0.19 and PyOD < 0.6.9, then you will see this error. We identified this error and addressed it in v0.6.9. See screenshot below.

![image](https://user-images.githubusercontent.com/15079146/57532938-9d73f400-730a-11e9-8a19-254a577449aa.png)

Can I ask you to update to PyOD v0.7.0 to see whether the issue is addressed? See documentation:  https://pyod.readthedocs.io/en/latest/pyod.models.html#module-pyod.models.cblof

**Comment by wbarich** [comment]
Thank you, my PyOD was not up to date with v0.7.0.

**Comment by emigre459** [comment]
I'm getting a similar final error with CBLOF `ValueError: Could not form valid cluster separation. Please change n_clusters or change clustering method`. I'm using pyod 0.7.7.1. Any thoughts? I've tried pre-training an sklearn KMeans (sklearn version 0.21.3) model that I pass in via the `clustering_estimator` argument too, but it still throws the same error. Perhaps the alpha and beta values are bad?

**Comment by yzhao062** [comment]
@emigre459 It is simply because the selected number of clusters does not form valid clusters for separation. I will suggest using a smaller number of "n_clusters". If it is Kmeans, try to run multiple times, maybe one of them gets converged.

**Comment by emigre459** [comment]
@yzhao062 Thanks for the quick reply! The number of clusters issue is exactly why I pre-trained a KMeans algorithm from sklearn with the number of clusters I wanted to use, to make sure it could converge before trying to pass it into CBLOF. I can confirm that `n_clusters=2` (passed either to CBLOF, the KMeans estimator itself, or both) still generates the error. Do you know of any other debugging I can try?

Also, for clarification: does the `n_ clusters` parameter in CBLOF do anything if you pass a trained model to `clustering_estimator`? I would have assumed `n_clusters` would be ignored in CBLOF in that case (since the cluster count would already be dictated by the model you pass in). Or does CBLOF re-train the model regardless of the model's pre-trained status perhaps? And if so, why would it be seeing a convergence error that sklearn itself isn't throwing?

**Comment by yzhao062** [comment]
It will refit anyway, so no pre-trained model is needed. Actually it is not about whether the clustering will converge. Kmeans generally converges. 

It is about how to differentiate "large clusters" from "small clusters". To decide that, there is a threshold should be calculated. I would see you could try to decrease "alpha" (the number of samples in large clusters to the number of samples in small clusters.) or decrease "beta" (Coefficient for deciding small and large clusters.) 

For instance, change alpha to 0.75 and change beta to 3.

**Comment by emigre459** [comment]
Ahhh, I see now. I was incorrectly interpreting the error. You're right, as soon as I change the beta and alpha parameters, I get a successful result. Thank you!
