### ISSUE TITLE
use the Pyod for timeseries anomaly detection 

### ISSUE THREAD

**Issue by FeizNouri** [yzhao062/pyod#9]
Hi
i'm looking for  toolkits for timeseries anomaly detection. is the Pyod provides timeseries anomaly detection??

**Comment by yzhao062** [comment]
Thanks for asking. Currently Pyod is not equipped with time series detection models. I am planning to add some time series (streaming data) detection methods soon. 

While waiting for the update, you may want to take a look at:

- https://github.com/MentatInnovations/datastream.io
- https://github.com/earthgecko/skyline
- https://github.com/tsurubee/banpei

Will update you again once streaming data outlier detection is in place.
Cheers.

**Comment by FeizNouri** [comment]
Thanks for replying, i took a look at the links it was helpful, thanks.

**Comment by earthgecko** [comment]
Hi @yzhao062 

Firstly, @FeizNouri sorry for hijacking this issue, however it is currently
the most appropriate and only place to address @yzhao062 on this issue.

I have been thinking about and looking at adding Pyod to a new branch in
Skyline probably as another set of algorithm/s in Analyzer and Mirage.  It would
be great to chat with you either here or in https://gitter.im/earthgecko-skyline/Lobby
and get some of your thoughts, opinions and ideas on how best I could go about
doing that.  I am certain that you will have a lot of useful insight that could
help me not have to totally reverse engineer Pyod and implement a OD streaming
method myself, which would enable me to iterate this addition to Skyline much
quicker.  Whenever evaluating anything in terms of Skyline, I find that for me
to really be able to include something, I literally have to reverse engineer
most of whatever it is I am trying to add to Skyline.  If I did not have to do
this with Pyod it would be most welcome.

What I really am looking for is mostly your opinion on what and how (i) outlier
detection algorithms; (ii) outlier ensemble frameworks and (iii) outlier
detection utility functions would be or could be best suited to be run in real
time against the time series.

I am wondering if I may be able to implement some Pyod functionally in Skyline
in a similar way to Skyline's curent 3-sigma based algorithms method.  Although
performance is a very important aspect of Skyline, so perhaps if any of Pyod's
methods are too CPU/time intensive a selection of the most appropriate method/s
could be used.

Further to this, I will probably try to include https://github.com/smirmik/CAD
(Task #2444: Evaluate CAD) with Pyod (Task #2436: Review Pyod) on this branch,
because as you can see they are both on my Skyline roadmap.  From my side it
makes sense to try and add them both to provide new algorithms to Skyline,
altough CAD will only add one new algorithm and Pyod could potentially add n.

To give you some further insight into this decision to add more algorithms to
Skyline I shall explain where I am thinking of going with this.  Apart from
perhaps making Skyine's anomaly detection better/more accurate, given that CAD
scores much higher on the NAB benchmark score than etsy/Skyline, earthgecko/skyline
arguably no longer fits ths NAB benchmark.  However, my motivation with these
additions is not focused on improving the anomaly detection per se.  Skyline
currently records all algorithms that trigger with each anomaly, e.g.

```python
['triggered_algorithms', ['first_hour_average', 'mean_subtraction_cumulation', 'stddev_from_average', 'stddev_from_moving_average', 'least_squares', 'histogram_bins']]
```

My intention is to use this to correlate anomalies/metrics with triggered
algorithms and use these to try and further train Skyline on anomalies, metrics,
algorihms and their relations in the metric population as a whole.  A branch I
am calling radiants.

So in simple terms, if Skyline triggers an anomaly on metric.x.cpu.total and the
following algorithms are triggered

```python
['triggered_algorithms', ['stddev_from_average', 'MCD', 'CAD']]
```

And we have the following cross correlated metrics to the anomaly on metric.x.cpu.total

```python
['correlation_metrics', ['metric.y.cpu.total', 'metric.y.eth0.txBytes', 'metric.x.eth0.rxBytes']]
```

We can allow the user to train Skyline on this pattern in terms of validating
anomalies or invalidating anomalies, in this way it should be possible to
further train Skyline to vastly improve its anomaly detection as a whole.  This
radiants branch will also add labeling to Skyline so that there is labeled
training data and "fingerprints" on anomalies in the future for possible use in
some future autoML context.

The recent addition of training Skyline on what is NOT anomalous using features
fingerprinting has been remarkably successful, I honestly think that being able
to add this described functionality will have similar overall results.  It would
be possible to achieve this with just the 3sigma algorithms undoubtedly, however
I am very keen to add some new algorithm methods to Skyline and Pyod and CAD
seem like they may be a good fit.

Anyway I hope that this may sound interesting enough for this conversation to be
continued.

Further this would in no way exclude the option of adding streaming data outlier
detection to Pyod itself and I would be happy to provide any assistance I could
to that endeavour if there was any value I could add.

**Comment by yzhao062** [comment]
@earthgecko thanks for reaching out. I have a very superficial understanding of skyline as a time-series/stream anomaly detection toolbox. pyod is not dealing with streaming data but multivariate data, such as a n samples with m features like a matrix. Just wonder what's your plan for including it as part of skyline given they have different targets? I may need some time to try skyline first to have a better understanding:)

**Comment by earthgecko** [comment]
Hi @yzhao062

Thanks for getting back to me on this.  I do not know exactly how to be honest,
but let me try and fit a round peg into a square hole.  In terms of Skyline,
Skyline holds and can calculate/determine additional data on the fly.

I think it should be possible to "add" multivariate data to every time series in
the population on the fly, as Skyline currently has the dimensions of triggered
algorithms and correlations.  So one idea is to try something like the following.
When a single metric triggers as an anomaly, Skyline stores an anomaly record.

Let us use a metric named stats.statsd.graphiteStats.flush_length which in the
Skyline database has the metric id of 26.  Let us say at 1534074138
stats.statsd.graphiteStats.flush_length triggered as anomalous and an anomaly
record was store as, e.g.

```
id,metric,anomaly_timestamp,anomalous_datapoint,triggered_algorithms
123,26,1534074138,3289.0,[1,2,3,6,7,9]
```

Now Skyline does not record triggered_algorithms from every metric, at every
data point, on every analysis.  However seeing has Skyline has all the time series data
available for every metric with 24 hours worth of data points for every metric,
~1450 data points per metric, when an anomaly triggers it would be possible
to analyse a time window of all the metrics and calculate the triggered
algorithms for each metric at every data point in the sample time window.  How
big a time window would be relevant, I do not know.

We could then have a data set per metric like(X,y), assume 0 as no triggered
algorithms, ```[timestamp, value], [[triggered_algorithms]]]```:

```
[[1534074108, 2687], [1534074118, 2687], [1534074128, 2687],
[1534074138, 3289]] [[0,0,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,0,0],
[1,2,3,6,7,9]]
```

Or if using just a count of the triggered algorithms, if a list of lists was not
appropriate, ```[timestamp, value], [triggered_algorithms_count]]```:

```
[[1534074108, 2687], [1534074118, 2687], [1534074128, 2687],
[1534074138,3289.0]] [0, 0, 0, 6]]
```

Further to that it would be possible to assign an anomaly score of 0 or 1 for
every metric and data point in addition to triggered_algorithms.  Skyline could
calculate these data quite easily for every metric.  Would it then be feasible
to analyse this type of data in a Pyod context?

The data could be presented in multiple formats, for instance, instead of the
timestamp being used in X, trigger_algorithms or a count thereof or the anomaly
score be used instead, ```[[triggered_algorithms], value], [anomaly_score]]```

```
[[[0,0,0,0,0,0], 2687], [[0,0,0,0,0,0], 2687], [[0,0,0,0,0,0], 2687],
[[1,2,3,6,7,9], 3289]] [0, 0, 0, 1]
```

And further to this a cross correlations data set could similiarly be created
if it was appropriate to use, ```[[correlated_metric_ids], value], [anomaly_score]]```

```
[[[0], 2687], [[0], 2687], [[0], 2687],
[[29,43,51], 3289]] [0, 0, 0, 1]
```

However, I am unsure of whether this type of data would suit Pyod to be quite
honest and whether it would result in useful information, although I am
interested to find.  How would one analyse say 4380 (X, y) matrices with Pyod
(where 4380 would be the number of data set Skyline could created if Skyline
were monitoring 4380 unique univariate metrics)? If any of the above was
feasible what would be the best suited Pyod method/s to use?  These are the key
questions that I have :)

I am mostly interested in determining if there is any way of using the current
data that Skyline has with Pyod in order to better understand the metric
population as a whole, especially in terms of learning relationships between
metrics.

Can we learn any relationships between the metrics based on a commonality of
some of them being outliers in the data set within the same time window, meaning
the machine_a.rxBytes has an outlier and machine_b.txBytes is also an outlier
(but possibly not an anomaly), from this over time we could possible learn that
machine_a.rxBytes and machine_b.txBytes are related to each other, especially if
we can relate this pattern together repeatedly and record these relationships.

I am not interest in Pyod in terms of detecting anomalies per se, I am more
interested in using it to possibly help describe relationships between the
metrics and anomalies and another form of labeling.  In terms the given example
of triggered_algorithms, well if machine_a.rxBytes was anomalous at x and it was
also an outlier in the population at x with y method, then that would be
considered as a triggered_algorithm.  The important thing to understand here is
that Skyline's development is not focused at anomaly detection.  That part is
done :) 3sigma catches ALL the anomalies you could ever want.  So we we go off
the basis that applying 3sigma methods is going to detect a very large
percentage of all the real, contextually relevant anomalies, along with a lot of
noise.  This allows us to look at the problem a bit differently, trying to
train the system on what is not anomalous, along with learning as much as we can
about the metric population to enable us to train the system on a single metric
behaviour that is not anomalous, however if we populate the system with other
types of data, over time can it learn, if we said machine_a.rxBytes was not
anomalous in some state and that machine_b.txBytes always behaves in it's own
distinct manner/pattern when machine_a.rxBytes  is in said state, then
machine_a.rxBytes is also probably not anomalous in it's state. where a state could
be described in a multivariate manner, e.g. (value, triggered_algorithms, etc).

Skyline is now more than simple detection, it is currently more focused on validation
and adding additional dimension to the detection methodology to try and make
alerting more reliable and also add additional data about the entire metric population
as a whole to better inform the user.

I am hoping Pyod make help in this regard :)

**Comment by dan-r95** [comment]
Is there any news on this @yzhao062 ?

**Comment by yzhao062** [comment]
A new library called Time Series Outlier Detection System (TODS) will be released in a few weeks. I think it will be some time in Sep, which is the PyOD counterpart for TS data.

**Comment by yzhao062** [comment]
TODS (https://github.com/datamllab/tods) is finally out. Please check out if you want to do TS OD.

**Comment by ogreyesp** [comment]
Hi @yzhao062 

I'm really interested in using PyOD or TODS for detecting outliers in multivariate timeseries data. However, I'm missing something. According to the official TODS's documentation:

"Wide-range of Algorithms, including all of the point-wise detection algorithms supported by PyOD, state-of-the-art pattern-wise (collective) detection algorithms such as DeepLog, Telemanon, and also various ensemble algorithms for performing system-wise detection."

So, if I could understand well, TODS currently uses PyOD to perform point-wise detection in time series data. However, as you mentioned before, PyOD doesn't handle time series data. So, my question is: Is TODS detecting outliers in time series data correctly?

Maybe this is not right place to put this question...

Best regards

**Comment by yzhao062** [comment]
close as we have developed TODS instead (https://github.com/datamllab/tods)
